name: Build custom armbian images
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install git -y
      - name: Clone repo
        run: |
          git clone --depth=1 --branch=main https://github.com/armbian/build
      - name: Build variants
        run: |
          cd build
          ./compile.sh BUILD_MINIMAL=yes BOARD=orangepi3b BRANCH=legacy KERNEL_ONLY=no RELEASE=jammy
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: "build/output/images/**"
          tag_name: release-${{ steps.date.outputs.date }}
