name: Build custom armbian images
on:
  workflow_dispatch:

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install git -y
      - name: Clone repo
        run: |
          git clone --depth=1 --branch=main https://github.com/armbian/build
      - name: Build variants
        run: |
          cd build
          # Server ubuntu old kernel
          ./compile.sh KERNEL_CONFIGURE=no BUILD_MINIMAL=yes BOARD=orangepi3b BRANCH=legacy RELEASE=jammy
          ./compile.sh KERNEL_CONFIGURE=no BUILD_MINIMAL=yes BOARD=orangepi3b BRANCH=legacy RELEASE=lunar
          ./compile.sh KERNEL_CONFIGURE=no BUILD_MINIMAL=yes BOARD=orangepi3b BRANCH=legacy RELEASE=mantic
          # Server debian old kernel
          ./compile.sh KERNEL_CONFIGURE=no BUILD_MINIMAL=yes BOARD=orangepi3b BRANCH=legacy RELEASE=bullseye
          ./compile.sh KERNEL_CONFIGURE=no BUILD_MINIMAL=yes BOARD=orangepi3b BRANCH=legacy RELEASE=bookworm
          # Server ubuntu new kernel
          ./compile.sh KERNEL_CONFIGURE=no BUILD_MINIMAL=yes BOARD=orangepi3b BRANCH=edge RELEASE=jammy
          ./compile.sh KERNEL_CONFIGURE=no BUILD_MINIMAL=yes BOARD=orangepi3b BRANCH=edge RELEASE=lunar
          ./compile.sh KERNEL_CONFIGURE=no BUILD_MINIMAL=yes BOARD=orangepi3b BRANCH=edge RELEASE=mantic
          # Server debian new kernel
          ./compile.sh KERNEL_CONFIGURE=no BUILD_MINIMAL=yes BOARD=orangepi3b BRANCH=edge RELEASE=bullseye
          ./compile.sh KERNEL_CONFIGURE=no BUILD_MINIMAL=yes BOARD=orangepi3b BRANCH=edge RELEASE=bookworm
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: "build/output/images/**"
          tag_name: release-${{ steps.date.outputs.date }}
